### ISSUE TITLE
MatchRegexp incorrect behavior

### ISSUE THREAD

**Issue by rschio** [yields/ant#27]
MatchRegexp function tries to match r.Host+r.Path, but the r.Path is normalized to not contain the leading slash.
So if the url := "https://google.com/search/car" and one tries to match with exp := regexp.QuoteMeta("google.com/search/car") it returns false because MatchRegexp is comparing "google.comsearch/car" with the exp.

**Comment by yields** [comment]
I added a test in https://github.com/yields/ant/commit/11ae3bb188354dd1c5fc8035fd547d02cf8a8590 to make sure the tests pass, they do, but after reading the docs for `(*url.URL).Path` it seems that in some situations it doesn't contain a leading slash.

So in https://github.com/yields/ant/commit/d9769806d08513744623b24467a0ad612b09ff1f I changed the `MatchRegexp` matcher to prepend a slash to all paths before comparing against the regex.

Thanks for the report! :)
