### ISSUE TITLE
Enhance Error Handling and Add Adaptive Retry Mechanism

### ISSUE THREAD

**Issue by fr3m2h** [yields/ant#49]
Currently, the error handling mechanism in the ant crawler could benefit from more detailed error messages and a robust retry mechanism. 

Proposed Enhancements:

    Descriptive Error Messages:
        Augment existing error messages with contextual information such as:
            The URL being crawled.
            HTTP status codes and headers for failed requests.
            Specific error types for network issues (e.g., DNS resolution failures, timeouts).

    Retry Mechanism:
        Implement an adaptive retry mechanism with the following features:
            Retry on specific HTTP status codes (e.g., 429 Too Many Requests, 500 Internal Server Error).
            Allow users to configure retry behavior via options such as:
                Maximum number of retries.
                Timeout between retries.

    Error Categories:
        Define structured error types to classify errors (e.g., NetworkError, HTTPError, TimeoutError) to make it easier for users to handle specific cases.

**Comment by yields** [comment]
Thanks man!

So the fetcher type can be configured with max attempts, max/min backoff. You can also override the fetcher client and provide your own retry.

Going to close but feel free to provide more details if there's a specific issue you're seeing.
