### ISSUE TITLE
Extend Protocol Support for Web Crawling

### ISSUE THREAD

**Issue by fr3m2h** [yields/ant#50]
The ant crawler primarily supports HTTP(S). Many modern web applications use other protocols such as WebSockets and gRPC to communicate and exchange data. Adding support for these protocols can significantly expand the usability of the ant crawler.

Proposed Enhancements:

    WebSocket Support:
        Enable crawling WebSocket-based endpoints to capture and process live data streams.
        Allow users to specify WebSocket-specific parameters, such as:
            Initial handshake headers.
            Subprotocols.

    gRPC Support:
        Allow the crawler to interact with gRPC endpoints for structured data collection.
        Provide options to:
            Specify gRPC service and method to invoke.
            Pass custom metadata and payloads.

    Modular Protocol Handling:
        Refactor the codebase to use a plugin-like architecture for protocols, making it easier to add support for additional protocols in the future (e.g., FTP, MQTT).

**Comment by yields** [comment]
Out of scope unfortunately.
